### ISSUE TITLE
Feature request: Configurable square to close gab between cleat an wall

### ISSUE THREAD

**Issue by AndreasMenz** [lizzard77/cnc-french-cleat-box-designer#1]
Very cool project! I'm sure a lot of users will benefit from it!
Unfortunately the french cleats in my shop are not directly attached to a flat wall but on a grid of vertical timbers
(Konterlattung in German).
So it would be nice if there was a small square at the bottom of the cleat thats configurable to close the gab between the cleat and the wall.

**Comment by lizzard77** [comment]
Thanks for your feedback - could you maybe attach a quick drawing (or modified SVG you downloaded from the website) so I can check what needs to be changed?

**Comment by AndreasMenz** [comment]
Hi, it seems that Github doesn't support SVG. I've added a PNG. I hope it explains my request
![SidePanel](https://user-images.githubusercontent.com/37173751/146155589-bf23a2d7-7863-4fb1-a635-5551dbe7747c.png)

**Comment by AndreasMenz** [comment]
The cherry on top of the cake would be if this project would also consider the diameter of the cutting bit in all the sharp corners!

**Comment by lizzard77** [comment]
Thanks Andreas - danke! The "bottom spacer" is a very good idea, actually my own wall has the same Konterlattung underneath. I never experienced problems as my current boxes are low enough.

Dog Bones for the sharp corners are prio #1 on my to do list. I'll keep you posted.

**Comment by lizzard77** [comment]
@AndreasMenz fixed and available for testing:

![image](https://user-images.githubusercontent.com/15921685/146534123-cf316a92-7402-4b36-86b1-0b7d65238a64.png)

**Comment by AndreasMenz** [comment]
@lizzard77 Wow, what a quick adjustment! Thank you!

To be honest, it's close, but not exactly what I had in mind. 
The basic idea was to have a support part, having an independent width compared to the cleat thickness. Of course it doesn't really matter to only adjust the cleat thickness, but in case of my shop, half of the cleat would be dangling in the air.

Here's another photo of a shelf for the shaper. If you look (very) closely, you can see the support part I attached:
![shaper_shelf](https://user-images.githubusercontent.com/37173751/146539773-838706f6-afa0-44e4-ae93-90c961de69eb.jpg)

**Comment by lizzard77** [comment]
Thanks for the photo, that's helpful. No problem, I can make both the height and the depth of the support part configurable. For my wall, that would have been the same value, but I see the two parts being different for your construction.

**Comment by lizzard77** [comment]
Does this cover your situation? In this example, I set "support part depth" to 45 to exaggerate the effect

![image](https://user-images.githubusercontent.com/15921685/146749347-a8013add-4c77-4bba-8e5a-8135e90b3a46.png)

**Comment by AndreasMenz** [comment]
This looks perfect to me! Thank you, this addition is going to be a decent time saver!
