### ISSUE TITLE
Possible to make it cuttable on CNC or Shaper Origin

### ISSUE THREAD

**Issue by jfearnside** [lizzard77/cnc-french-cleat-box-designer#2]
I love this project but the files are not cuttable using my shaper origin. This part is uncuttable due to the round cutting bit. WOuld it be possible to have an option to make it compatible with round cutting bits? 
![image](https://user-images.githubusercontent.com/29286841/149707602-ba529f06-902c-4823-a72a-5fa387fbcc9f.png)

Shaper has this design for their cleats. This is cuttable with a round bit. 
![image](https://user-images.githubusercontent.com/29286841/149707759-c0c8f32e-9e28-4d86-9ad5-f01e573669bc.png)

**Comment by lizzard77** [comment]
Thanks for your input - yes, a "Dogbones" like feature is prio #1 on my list for development. Can you send me a link to the Shaper design you referenced, that's a nice dogbone style I might adapt here....

**Comment by lizzard77** [comment]
Tipp: Until now, I handled that corner on the machine. Just pull it over the corner, offset the tool path by half the cutter diameter (i.e. -3mm), and plunge into the corner. That creates a nice dogbone without chaning the SVG

**Comment by jfearnside** [comment]
Link ot the french cleat files on shaper hub. https://hub.shapertools.com/creators/5d68222279a38a000faca8ca/shares/5e8b7845254f6b000fe63da7

**Comment by lizzard77** [comment]
I've just added dogbones to the sharp corners on the backside of the side panels - should be a first step. If that's what you imagined, I would add the gaps to the shelves as well...

**Comment by lizzard77** [comment]
Latest version includes dogbones, also for the shelves and bars - have fun!
